apiVersion: v1
kind: Namespace
metadata:
  name: #{Release.EnvironmentName}#
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: beerme
  labels:
    app: beerme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beerme
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: beerme
    spec:
      containers:
      - name: beerme
        image: glantzgaming.azurecr.io/beerme:#{Release.Artifacts.Beer.BuildId}#
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: beerme
  labels:
    app: beerme
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: beerme
